#!/bin/sh

# Set environment variables for motorboot application

export FLASK_APP_MODE=production
export FLASK_APP_KEY=toomanysecrets
export FLASK_APP_LOGDIR=default
export FLASK_COVERAGE=0
export APPSECRETS=.secrets.yml
