#!/bin/sh

# Set environment variables for poolparty application

export FLASK_APP_MODE=default
export FLASK_COVERAGE=0
export SQLALCHEMY_DATABASE_URI=sqlite:///motorboot_dev.sqlite
export BOOTFILES=bootfiles
