"""empty message

Revision ID: 34af67c37118
Revises: 
Create Date: 2017-03-18 20:39:28.864999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34af67c37118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.Column('hwaddress', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('hwaddress')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hosts')
    # ### end Alembic commands ###
